-- This file is retained for reference only.
-- The canonical schema is managed via versioned migrations in supabase/migrations/.
-- Apply with: supabase db push
--
-- To add a new change, run: supabase migration new <name>
